features/buyTicket.feature
Added scenarios about the buying tickets feature
=> New scenarios

features/listMovies.feature
fix errors in listMovies.feature
- [ x] Bug fix (non-breaking change which fixes an issue)
- [ x] I have performed a self-review of my own code
- [ x] I have checked my code and corrected any misspellings
=>  fix errors in listMovies.feature

features/registerMovie.feature, features/registerNewMovie.feature
Created registeredNewMovie.feature and added scenarios with specific paths. This is the foundation of the feature.
Review the scenarios created checking whether they follow the correct pattern and cover all of the possible paths for this feature.
=> Added registerNewMovie feature with scenarios

client/src/app/app.component.html, client/src/app/app.module.ts, client/src/app/common/badge/badge.component.html, client/src/app/common/badge/badge.component.scss, client/src/app/common/badge/badge.component.spec.ts, client/src/app/common/badge/badge.component.ts, package-lock.json
=> feat(main): create badge component

client/src/app/app-routing.module.ts, client/src/app/app.module.ts, client/src/app/components/ticket-card/ticket-card.component.html, client/src/app/components/ticket-card/ticket-card.component.scss, client/src/app/components/ticket-card/ticket-card.component.spec.ts, client/src/app/components/ticket-card/ticket-card.component.ts, client/src/app/pages/tickets/tickets.component.html, client/src/app/pages/tickets/tickets.component.scss, client/src/app/pages/tickets/tickets.component.spec.ts, client/src/app/pages/tickets/tickets.component.ts
=> feat(tickets): create page and components

client/src/app/app-routing.module.ts, client/src/app/app.module.ts, client/src/app/pages/payment/payment.component.html, client/src/app/pages/payment/payment.component.scss, client/src/app/pages/payment/payment.component.spec.ts, client/src/app/pages/payment/payment.component.ts
=> Payment screen

client/src/app/components/seat/seat.component.scss, client/src/app/components/seat/seat.component.ts, client/src/app/pages/checkout/checkout.component.html, client/src/app/pages/checkout/checkout.component.scss, client/src/app/pages/checkout/checkout.component.ts
=> feature: checkout page

client/src/app/app-routing.module.ts, client/src/app/pages/movie/movie.component.html, client/src/app/pages/movie/movie.component.scss, client/src/app/pages/movie/movie.component.ts
- [ X] New feature (non-breaking change which adds functionality)
=> feat(movie): add session pick to movie page

client/src/app/pages/checkout/checkout.component.html, client/src/app/pages/checkout/checkout.component.scss
=> feat(checkout-page-fixes) added select component

server/config/app.js, server/controllers/ticketsController.js, server/models/Ticket.js, server/repositories/ticketsRepositories.js, server/routes.js
=> feat(tickets-db): create tickets

client/src/app/components/card-movie/card-movie.component.html, client/src/app/components/card-movie/card-movie.component.ts, client/src/app/pages/home/home.component.html, client/src/app/pages/movie/movie.component.html, client/src/app/pages/movie/movie.component.ts, client/src/app/services/api/types.ts
=> feat(movie-page): get id and integrate

client/src/app/pages/signup/signup.component.html, client/src/app/pages/signup/signup.component.scss, client/src/app/services/auth/auth.service.ts
=> feat(movie-page): add signup info

client/src/app/pages/checkout/checkout.component.html, client/src/app/pages/checkout/checkout.component.ts
=> feat(live-update) update tickets total

client/src/app/pages/add-movie/add-movie.component.html, client/src/app/pages/checkout/checkout.component.scss, client/src/app/pages/payment/payment.component.html, client/src/app/pages/payment/payment.component.ts, client/src/app/pages/signin/signin.component.html, client/src/app/pages/signin/signin.component.scss, client/src/app/pages/signup/signup.component.html
=> Card infos

client/src/app/pages/checkout/checkout.component.html, client/src/app/pages/checkout/checkout.component.ts
=> feat(checkout page) seat numbers control

client/src/app/pages/payment/payment.component.html
=> feat card number

client/src/app/pages/tickets/tickets.component.ts, client/src/app/services/api/api.service.ts, client/src/app/services/api/types.ts
=> feat(add-movie): create tickets api calls

client/src/app/components/ticket-card/ticket-card.component.ts, client/src/app/pages/add-movie/add-movie.component.ts, client/src/app/pages/signin/signin.component.html, client/src/app/pages/signin/signin.component.scss, client/src/app/pages/tickets/tickets.component.html, client/src/app/pages/tickets/tickets.component.ts, client/src/app/services/api/api.service.ts, client/src/app/services/api/types.ts, server/repositories/ticketsRepositories.js
=> feat(create-ticket): get tickets

client/src/app/pages/checkout/checkout.component.html, client/src/app/pages/checkout/checkout.component.ts, client/src/app/services/api/types.ts
=> feat(checkout page) send tickets to backend

features/buyTicket.feature, features/listMovies.feature, features/registerNewMovie.feature, features/unavailableSession.feature, features/userAuthentication.feature
=> feat(update-features) fixing the features

client/src/app/pages/checkout/checkout.component.ts, client/src/app/pages/movie/movie.component.html, client/src/app/pages/movie/movie.component.ts, client/src/app/services/api/types.ts, client/tsconfig.json
=> feat(movie): get sessions

client/src/app/app-routing.module.ts, client/src/app/pages/checkout/checkout.component.ts, client/src/app/pages/movie/movie.component.ts, client/src/app/services/api/api.service.ts
=> checkout page fixes 

client/src/app/pages/tickets/tickets.component.ts, client/src/app/services/api/api.service.ts, server/repositories/ticketsRepositories.js
=> feat(checkout page) tickets show up on tickets page

client/src/app/pages/checkout/checkout.component.ts
=> feat(checkout page) movie id on ticket

client/src/app/common/navbar/navbar.component.spec.ts, client/src/app/pages/add-movie/add-movie.component.spec.ts, client/src/app/pages/checkout/checkout.component.spec.ts, client/src/app/pages/checkout/checkout.component.ts, client/src/app/pages/home/home.component.spec.ts, client/src/app/pages/management/management.component.spec.ts, client/src/app/pages/movie/movie.component.spec.ts, client/src/app/pages/signin/signin.component.spec.ts, client/src/app/pages/signup/signup.component.spec.ts, client/src/app/pages/tickets/tickets.component.spec.ts, client/src/app/services/api/api.service.spec.ts, client/src/app/services/auth/auth.service.spec.ts, server/controllers/moviesController.js, server/controllers/ticketsController.js
=> feat(tests): remove imports error

client/src/app/components/ticket-card/ticket-card.component.html, client/src/app/components/ticket-card/ticket-card.component.scss, client/src/app/components/ticket-card/ticket-card.component.ts, client/src/app/pages/tickets/tickets.component.ts, package-lock.json, server/controllers/moviesController.js, server/routes.js
=> feat(ticket-pdf): update funcionalities

client/src/app/services/auth/auth.service.spec.ts, client/src/app/services/auth/auth.service.ts
=> feat(tests): fix tests

server/controllers/moviesController.js, server/routes.js
=> feat(tests): add getPossibleHours

server/controllers/ticketsController.js
=> feat(tests): add update movie

client/src/app/pages/checkout/checkout.component.html, client/src/app/pages/checkout/checkout.component.ts, client/src/app/pages/payment/payment.component.ts
=> feat(delete-button) routes bug fix

server/controllers/moviesController.spec.js, server/controllers/ticketsController.spec.js, server/package-lock.json, server/package.json, server/yarn.lock
=> feat(management-movies): create tests

client/src/app/common/navbar/navbar.component.spec.ts, client/src/app/pages/checkout/checkout.component.html, client/src/app/pages/checkout/checkout.component.ts, client/src/app/pages/movie/movie.component.ts, client/src/app/pages/tickets/tickets.component.ts, client/src/app/services/auth/auth.service.ts, server/controllers/moviesController.js
=> feat(seats): add unavailable seats

client/src/app/pages/checkout/checkout.component.ts, client/src/app/pages/management/management.component.ts, client/src/app/pages/movie/movie.component.ts, client/src/app/services/api/types.ts
=> feat(seats): fix create ticket

README.md
- [ X] I have performed a self-review of my own code
=> feat(update-readme): detailed run server description
